const songsByYear = [
    
{ year: 1960, song: "Theme from A Summer Place", artist: "Percy Faith" },
{ year: 1961, song: "Tossin' and Turnin'", artist: "Bobby Lewis" },
{ year: 1962, song: "I Can't Stop Loving You", artist: "Ray Charles" },
{ year: 1963, song: "Sugar Shack", artist: "Jimmy Gilmer and The Fireballs" },
{ year: 1964, song: "I Want to Hold Your Hand", artist: "The Beatles" },
{ year: 1965, song: "Wooly Bully", artist: "Sam the Sham and The Pharaohs" },
{ year: 1966, song: "The Ballad of the Green Berets", artist: "SSgt Barry Sadler" },
{ year: 1967, song: "To Sir With Love", artist: "Lulu" },
{ year: 1968, song: "Hey Jude", artist: "The Beatles" },
{ year: 1969, song: "Sugar, Sugar", artist: "The Archies" },
{ year: 1970, song: "Bridge Over Troubled Water", artist: "Simon & Garfunkel" },
{ year: 1971, song: "Joy to the World", artist: "Three Dog Night" },
{ year: 1972, song: "The First Time Ever I Saw Your Face", artist: "Roberta Flack" },
{ year: 1973, song: "Tie a Yellow Ribbon Round the Ole Oak Tree", artist: "Dawn featuring Tony Orlando" },
{ year: 1974, song: "The Way We Were", artist: "Barbra Streisand" },
{ year: 1975, song: "Love Will Keep Us Together", artist: "Captain & Tennille" },
{ year: 1976, song: "Silly Love Songs", artist: "Wings" },
{ year: 1977, song: "Tonight's the Night (Gonna Be Alright)", artist: "Rod Stewart" },
{ year: 1978, song: "Shadow Dancing", artist: "Andy Gibb" },
{ year: 1979, song: "My Sharona", artist: "The Knack" },
{ year: 1980, song: "Call Me", artist: "Blondie" },
{ year: 1981, song: "Bette Davis Eyes", artist: "Kim Carnes" },
{ year: 1982, song: "Physical", artist: "Olivia Newton-John" },
{ year: 1983, song: "Every Breath You Take", artist: "The Police" },
{ year: 1984, song: "When Doves Cry", artist: "Prince" },
{ year: 1985, song: "Careless Whisper", artist: "Wham! featuring George Michael" },
{ year: 1986, song: "That's What Friends Are For", artist: "Dionne and Friends" },
{ year: 1987, song: "Walk Like an Egyptian", artist: "The Bangles" },
{ year: 1988, song: "Faith", artist: "George Michael" },
{ year: 1989, song: "Look Away", artist: "Chicago" },
{ year: 1990, song: "Hold On", artist: "Wilson Phillips" },
{ year: 1991, song: "(Everything I Do) I Do It for You", artist: "Bryan Adams" },
{ year: 1992, song: "End of the Road", artist: "Boyz II Men" },
{ year: 1993, song: "I Will Always Love You", artist: "Whitney Houston" },
{ year: 1994, song: "The Sign", artist: "Ace of Base" },
{ year: 1995, song: "Gangsta's Paradise", artist: "Coolio featuring L.V." },
{ year: 1996, song: "Macarena (Bayside Boys Mix)", artist: "Los del Río" },
{ year: 1997, song: "Candle in the Wind 1997", artist: "Elton John" },
{ year: 1998, song: "Too Close", artist: "Next" },
{ year: 1999, song: "Believe", artist: "Cher" },
{ year: 2000, song: "Breathe", artist: "Faith Hill" },
{ year: 2001, song: "Hanging by a Moment", artist: "Lifehouse" },
{ year: 2002, song: "How You Remind Me", artist: "Nickelback" },
{ year: 2003, song: "In da Club", artist: "50 Cent" },
{ year: 2004, song: "Yeah!", artist: "Usher featuring Lil Jon and Ludacris" },
{ year: 2005, song: "We Belong Together", artist: "Mariah Carey" },
{ year: 2006, song: "Bad Day", artist: "Daniel Powter" },
{ year: 2007, song: "Irreplaceable", artist: "Beyoncé" },
{ year: 2008, song: "Low", artist: "Flo Rida featuring T-Pain" },
{ year: 2009, song: "Boom Boom Pow", artist: "The Black Eyed Peas" },
{ year: 2010, song: "Tik Tok", artist: "Ke$ha" },
{ year: 2011, song: "Rolling in the Deep", artist: "Adele" },
{ year: 2012, song: "Somebody That I Used to Know", artist: "Gotye featuring Kimbra" },
{ year: 2013, song: "Thrift Shop", artist: "Macklemore & Ryan Lewis featuring Wanz" },
{ year: 2014, song: "Happy", artist: "Pharrell Williams" },
{ year: 2015, song: "Uptown Funk", artist: "Mark Ronson featuring Bruno Mars" },
{ year: 2016, song: "Love Yourself", artist: "Justin Bieber" },
{ year: 2017, song: "Shape of You", artist: "Ed Sheeran" },
{ year: 2018, song: "God's Plan", artist: "Drake" },
{ year: 2019, song: "Bad Guy", artist: "Billie Eilish" },
{ year: 2020, song: "Blinding Lights", artist: "The Weeknd" },
{ year: 2021, song: "Drivers License", artist: "Olivia Rodrigo" },
{ year: 2022, song: "As It Was", artist: "Harry Styles" },
{ year: 2023, song: "Mona Lisa", artist: "Dominic Fike"}
];

export default songsByYear;
  